version = "3.11.5"
runner.dialect = scala213

maxColumn = 100

project.includePaths."+" = ["glob:**.md"]

indent {
  main = 2
  callSite = 2
  defnSite = 2
  caseSite = 2
  ctorSite = 2
  extendSite = 2
  withSiteRelativeToExtends = 0
  relativeToLhsLastLine = [match, infix]
}

align {
  preset = more
  multiline = true
  inInterpolation = true
}

newlines {
  source = fold
  selectChains.style = unfold

  configStyle {
    defnSite.prefer = true
    callSite.prefer = true
  }
}

danglingParentheses {
  defnSite = true
  callSite = true
  bracketDefnSite = true
  bracketCallSite = true
  ctrlSite = true
  tupleSite = true
}

binPack {
  defnSite = Never
  callSite = Never
  importSelectors = singleLine
  parentConstructors = ForceBreak
}

docstrings {
  oneline = fold
  wrap = yes
  blankFirstLine = fold
  style = SpaceAsterisk
}

rewrite {
  rules = [
    Imports,
    PreferCurlyFors,
    RedundantBraces,
    RedundantParens,
    SortModifiers,
  ]

  imports {
    selectors = keep
    sort = ascii
    removeRedundantSelectors = true
  }

  redundantBraces.preset = all
  redundantParens.preset = all
  sortModifiers.preset = styleGuide
  trailingCommas.style = never
}

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}
