version = "3.11.5"
runner.dialect = scala213

maxColumn = 100

indent {
  main = 2
  callSite = 2
  defnSite = 2
  caseSite = 2
  ctorSite = 2
}

align.preset = none

newlines {
  source = fold

  configStyle {
    defnSite.prefer = true
    callSite.prefer = true
  }
}

danglingParentheses {
  defnSite = true
  callSite = true
}

binPack {
  defnSite = Never
  callSite = Never
  importSelectors = singleLine
}

rewrite.trailingCommas.style = never
rewrite.imports.expand = false

fileOverride {
  "glob:**/*.sbt" {
    runner.dialect = sbt1
  }
}
