import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

export const STATE_DIR_ENV = "OMP_COLLAB_TUNNEL_STATE_DIR";

export interface TunnelStatePaths {
	config: string;
	pid: string;
}

export function defaultStateDir(env: NodeJS.ProcessEnv = process.env, home = os.homedir()): string {
	return env[STATE_DIR_ENV] || path.join(home, "Library", "Application Support", "omp-collab-tunnel");
}

export function statePaths(stateDir = defaultStateDir()): TunnelStatePaths {
	return {
		config: path.join(stateDir, "config.yml"),
		pid: path.join(stateDir, "pid"),
	};
}

export function collabConfigOverlay(relayUrl: string): string {
	if (!/^wss:\/\/[A-Za-z0-9.-]+(?::\d+)?$/.test(relayUrl)) {
		throw new Error(`refusing to publish invalid collab relay URL: ${relayUrl}`);
	}
	return `# Generated by omp-collab-tunnel while its Cloudflare Quick Tunnel is running.\n# Removed automatically on clean shutdown. Do not edit.\ncollab:\n  relayUrl: ${relayUrl}\n`;
}

export async function writeTunnelState(relayUrl: string, stateDir = defaultStateDir(), pid = process.pid): Promise<TunnelStatePaths> {
	const paths = statePaths(stateDir);
	await mkdir(stateDir, { recursive: true });
	const suffix = `${pid}.${Date.now()}`;
	const tmpConfig = `${paths.config}.${suffix}.tmp`;
	const tmpPid = `${paths.pid}.${suffix}.tmp`;
	await writeFile(tmpConfig, collabConfigOverlay(relayUrl), { mode: 0o600 });
	await writeFile(tmpPid, `${pid}\n`, { mode: 0o600 });
	await rename(tmpConfig, paths.config);
	await rename(tmpPid, paths.pid);
	return paths;
}

export async function clearTunnelState(stateDir = defaultStateDir()): Promise<void> {
	const paths = statePaths(stateDir);
	await Promise.all([rm(paths.config, { force: true }), rm(paths.pid, { force: true })]);
}
